title: Fredrick Fuchs
description: Ultra-high-energy cosmic rays, neutrino physics, and detector development
theme: jekyll-theme-minimal

logo: /Screenshot%202026-01-07%20192807.png

show_downloads: false

github:
  is_project_page: false
