title: Fredrick Fuchs
description: Ultra-high-energy cosmic rays, neutrino physics, and detector development
theme: jekyll-theme-minimal

logo: /assets/images/profile.jpg

show_downloads: false

github:
  is_project_page: false
